<footer>
  <a href="mailto:teamzerocool@thenet.ca">Copyright &copy; zerocool 2014.</a>
  <a href="#top">Back to Top</a>
  <a href="http://validator.w3.org/check?uri=referer">Validate this Page</a>
  <div class="validator">
    <a href="http://validator.w3.org/check?uri=referer">
      <img
        src="images/html5_logo_32.png"
        alt="Valid HTML 5!" height="32" width="32" />
    </a>
  </div>
</footer>