 <nav id="mainnav">
  <ul>
    <li>
      <a id="indexnav" href="index.shtml">Home</a>
    </li>
    <li>
      <a id="wireframenav" href="wireframe.shtml">Wireframe</a>
    </li>
    <li>
      <a id="protositenav" href="protosite/index.shtml">Protosite</a>
    </li>
    <li>
      <a id="rationalenav" href="rationale.shtml">Rationale</a>
    </li>
    <li>
      <a id="sitemapnav" href="sitemap.shtml">Sitemap</a>
    </li>
  </ul>
</nav>