     <nav id="secondnav">
            <ul>
                <li>
                    <a id="indexnav1" href="index.shtml">Home</a>
                </li>
                <li>
                    <a id="wireframenav1" href="wireframe.shtml">Wireframe</a>
                </li>
                <li>
                    <a id="protositenav1" href="protosite/index.shtml">Protosite</a>
                </li>
                <li>
                    <a id="rationalenav1" href="rationale.shtml">Rationale</a>
                </li>
                <li>
                    <a id="sitemapnav1" href="sitemap.shtml">Sitemap</a>
                </li>
            </ul>
        </nav>