<br style="clear:both" />
<br />

<footer>
  <div>
    <nav>
      <ul class="listMenu">
        <li class="currentpage">
          <a href="index.shtml">Home</a>
        </li>
        <li>
          <a href="lectures.shtml">Lectures</a>
        </li>
        <li>
          <a href="#">Blog</a>
        </li>
        <li>
          <a href="contact.shtml">Contact</a>
        </li>

        <li>
          <a href="#">Wiki/Forums</a>
        </li>
        <li>
          <a href="#">Alumni Resources</a>
        </li>
        <li>
          <a href="#">Sitemap</a>
        </li>
      </ul>
    </nav>
  </div>
</footer>

<div class="validator">
  <a href="http://validator.w3.org/check?uri=referer">
    <img
      src="images/html5_logo_32.png"
      alt="Valid HTML 5!" height="32" width="32" />
  </a>
</div>