<div id="menu">
  <nav>
    <ul class="listMenu">
      <li id="logo">
        <a href="http://www.bcit.ca/">
          <img  src="images/logobcit.jpg" alt="BCIT Logo" />
        </a>
      </li>
      <li class="currentpage">
        <a href="index.shtml">Home</a>
      </li>
      
      
      <li class="popupmenu">
        <a href="lectures.shtml">Lectures</a>
        
        <div id="lecturemenu">
          <ul id="tt">
            <li>
              <a href="week1.shtml">Week 1</a>
            </li>
            <li>
              <a href="week2.shtml">Week 2</a>
            </li>
            <li>
              <a href="week3.shtml">Week 3</a>
            </li>
          </ul>
        </div>
      </li>
      
      
      <li>
        <a href="#">Blog</a>
      </li>
      <li>
        <a href="contact.shtml">Contact</a>
      </li>
      </li>
      <li>
        <a href="#">Wiki/Forums</a>
      </li>
      <li>
        <a href="#">Alumni Resources</a>
      </li>
    </ul>
  </nav>
</div>