<div id="menu">
  <nav>
    <ul class="listMenu">
      <li class="currentpage">
        <a href="index.shtml">Home</a>
      </li>
      <li>
        <a href="lectures.shtml">Lectures</a>
        <div class="popupmenu">
          <ul>
            <li>
              <a href="week1.html">Week 1</a>
            </li>
            <li>
              <a href="week2.html">Week 2</a>
            </li>
            <li>
              <a href="week3.html">Week 3</a>
            </li>
          </ul>
        </div>
      </li>
      <li>
        <a href="#">Blog</a>
      </li>
      <li>
        <a href="contact.shtml">Contact</a>
      </li>
    </ul>
  </nav>
</div>